### ISSUE TITLE
Add command to display navigation back/forward history

### ISSUE THREAD

**Issue by mattstermiller** [mattstermiller/koffee#20]
Pressing `gh` will open a listing of the back and forward stacks in a panel similar to bookmarks. This panel will stay open while the user navigates back or forward, until some other command is done or `Esc` is pressed.

It should be shown as in the below mock-up (note the exquisite hand-drawn quality):
Two columns, Back on the left, Forward on the right. Each stack should be shown with the next items on top, showing at most 5 items. It should use the same styling as Bookmarks.

![image](https://user-images.githubusercontent.com/2790867/96317345-7710b880-0fd4-11eb-80ee-2d64c18fbf23.png)

**Comment by mattstermiller** [comment]
Instead of a command, maybe it could displayed as long as Shift is held after going back or forward.

**Comment by jilleJr** [comment]
How do you plan how the user selects which history to visit? Should it just be a display, expecting the user to traverse the list with `H` and `L`? 

What about existing keybindings? Should they close the history panel and operate in the main folder view or work inside the folde rview?

- What about `k` and `j`? Ex: work act as aliases for `H` and `L`, or just select different history items and relying on `<Enter>` to select it
- What about `/`, `f`, and `F`? Ex: search the history
- What about `<Delete>` and `<s-Delete>`? Ex: remove items from history
- What about `y`? Ex: copy a history path, works well if the panel is in a select mode.
- _et.al._

**Comment by jilleJr** [comment]
Ah wait it says it right there in the description! 

> This panel will stay open /.../ until some other command is done or `Esc` is pressed

Ignore my previous comment.

I would like to dibs this issue :)

**Comment by mattstermiller** [comment]
Correct, it should just provide visibility into the history stacks as a non-interactive "pop-up" like bookmarks. The existing commands for back/forward are to be used.

I added more to the description to specify how many and in what order to show items.

**Comment by mattstermiller** [comment]
> until some other command is done
I suppose I should define this a bit better. To avoid sprinkling code to set a model property to show the history to false everywhere, it might be better to have something in the dispatcher that does that for all Bindable commands except back/forward. That seems like the best idea to me at the moment, anyway.

**Comment by jilleJr** [comment]
OK I see your mockup, but I counter with a mockup idea of my own:

![image](https://user-images.githubusercontent.com/2477952/96339754-d3d4a780-1096-11eb-8f44-14b4f806715a.png)

Figure the "forward" feature would be very rarely used, and if implemented correctly it would just look like it's traversing up and down in the list. It goes back to the idea I had in my first comment there.
What do you think?

I do not fully understand what you mean there about sprinkling code. Can't really imagine the implementation you explain fully. Would be nice to be able to have some kind of dispatcher chain or something, where if you have history panel open the history dispatcher takes over control and can then chose to absorb or pass-through events. Like for example:

```fs
let rec historyPanelDispatcher innerDispatcher evt =
    let isHistoryNavigationChord =
        // todo

    let handleKeyPress chord handler model =
        // todo

    let disableHistoryPanelAndPassThrough chord handler model =
        let newModel = { model with Dispatcher = innerDispatcher }
        innerDispatcher (KeyPress (chord, handler)) newModel

    match evt with
    | KeyPress (chord, handler) when isHistoryNavigationChord chord -> handleKeyPress chord handler
    | KeyPress (chord, handler) -> disableHistoryPanelAndPassThrough
    | _ -> innerDispatcher evt
```

^ This reminds me of a stack-based FSM design pattern. Maybe that would be well suited here?

**Comment by mattstermiller** [comment]
Ah, a single stack makes a lot more sense! I love the mockup. The number of entries will still need to be limited, so keep that in mind. Also, paths can get very long, so we'll have to come up with a way to handle paths that don't fit in the panel. Maybe simply showing the last part will suffice. We can leave more horizontal room in the panel by moving the "Back" and "Forward" indicators to the top and bottom of the list, respectively.

My comment about "sprinkling code everywhere" was referring to avoiding putting code in every event handling function to hide the history panel. I'm not sure how I feel about your `historyPanelDispatcher`. My thought was just to insert a little bit of logic in the existing one, but if it turns out that it's cleaner your way, let's try it out.

**Comment by jilleJr** [comment]
Alright, I'll try implement my suggestion there, and if it fails I'll try your suggestion.

Would be grand to show relative paths, like if the list was:

- `../../Program Files/`
- `./Downloads/``
- `/c/Users/kalle/`
- `./Documents/`
- current: `/c/Users/kalle/`

For shortening long paths it would be good to shorten the beginning. I've also seen a nice version of shortening in the middle. Something like this:

- Full: C:/Users/kalle/AppData/Roaming/Koffee
- Shortened beginning: .../Roaming/Koffee
- Shortened middle: C:/Users/.../Koffee
- p10k style shortening: C:/U/k/A/R/Koffee (see [romkatv/powerlevel10k](https://github.com/romkatv/powerlevel10k#current-directory-that-just-works))

Don't know how to handle if the path is still too long after shortening the paths, nor how to check the length of the actual path. Maybe there's some good API's for it in System.Drawing. I don't know enough WPF to know how to accomplish this but I'll do some RnD on it. There could still be long folder names where they have to be trimmed as well, something like:

- Full: C:/Users/kalle/SomeReallyLongPathNameThatWontFitInTheHistoryView
- Shortened beginning: ...hatWontFitInTheHistoryView
- Shortened middle: C:/.../SomeReall...istoryView
- p10k style shortening: C:/U/k/A/R/S

**Comment by mattstermiller** [comment]
I feel like the relative paths might get confusing. I like the shortened middle, and if space is tight, beginning.
