### ISSUE TITLE
Remember sort per folder

### ISSUE THREAD

**Issue by mattstermiller** [mattstermiller/koffee#63]
Sort column and direction is not currently persisted, and when set, stays across all folders until changed again. This enhancement would make Koffee's sort work more like Windows Explorer: treat each folder as having its own sort setting and persist it.

Add a `PathSort` property to History as a tuple of Path, Sort, bool (descending). When changing the sort by anything other than Name ascending, add it to the list. When sorting by Name ascending, remove it from the list since that is the default and to keep the list size down.

**Comment by jilleJr** [comment]
I'd like to look into implementing this, if you're not already working on it.
I.e.: I call dibs

**Comment by mattstermiller** [comment]
It's yours, thanks! I'm not working on any help-wanted issues. I'm on #70
