### ISSUE TITLE
Follow links

### ISSUE THREAD

**Issue by mattstermiller** [mattstermiller/koffee#8]
Opening a shortcut (.lnk) would open the path that it points to. Implementing this doesn't look as easy as it should be.

**Comment by guiri14** [comment]
Just ran into this issue, went to post it, already exists

**Comment by guiri14** [comment]
So I think I have something more than a "metoo" post.  I checked out 
https://stackoverflow.com/questions/6141821/run-application-via-shortcut-using-process-start-c-sharp
And this lead me to m aking the following change in `FileSystemService.fs`

```
member this.OpenFile path =
    ProcessStartInfo(wpath path, WorkingDirectory = wpath path.Parent, UseShellExecute = true)
    |> Process.Start |> ignore
```

In particular, I added `UseShellExecute = true`.  There are some trade-offs, I think, listed here:
https://msdn.microsoft.com/en-us/library/system.diagnostics.processstartinfo.useshellexecute(v=vs.110).aspx

This allowed me to follow links happily and didn't seem to upset my ability to open anything else.  The next question is how to open files with administrative privelage I think.

**Comment by guiri14** [comment]
Actually I just tried executing a .lnk file on my normal install of Koffee and it worked fine... And the default for `UseShellExecute` is `true`.  So, nevermind, I'm left more confused.

**Comment by mattstermiller** [comment]
I think we talked about this in person, but to clarify here: koffee seems to have no problems opening files pointed to by shortcuts, but not folders. Instead of navigating to the folder the shortcut points to, it opens the folder in Windows Explorer. Not what I want LOL.
