### ISSUE TITLE
Allow removing path history

### ISSUE THREAD

**Issue by mattstermiller** [mattstermiller/koffee#81]
- When path suggestions from history are shown, pressing `Delete` should remove the selected entry.
- When attempting to open a path from history fails, the current location and path box text should not change.

**Comment by jilleJr** [comment]
When does Koffee provide path suggestions?

**Comment by mattstermiller** [comment]
It's described in detail in the README.

> Path Box Suggestions will appear when typing in the path box.
> 
> - When no slashes are in the path box, folders that you have visited before are searched. Folders starting with the first search term are shown first, then other matches sorted by most recently visited.
> - When a path is in the path box, everything after the last slash is used to search the folder before the last slash. For example, typing "C:\Windows\sy 32" would suggest "C:\Windows\System32".
> - When suggestions are shown, use the up and down arrow keys to select a suggestion. When there is only one suggestion, it is selected automatically.
> - Press Tab to fill in the path box with the selected suggestion and continue typing, or press Enter to open the selected suggestion.
