### ISSUE TITLE
Considered Hacktoberfest? Missing "topic" on repo :)

### ISSUE THREAD

**Issue by jilleJr** [mattstermiller/koffee#89]
Hi!

[Hacktoberfest](https://hacktoberfest.digitalocean.com/) has begun and I'm interested in tackling some of the issues on this repo, if you're up for taking contributions.

[According to their website](https://hacktoberfest.digitalocean.com/details#maintainers), a repo is only eligible for Hacktoberfest if it has the `#hacktoberfest` topic specified.

Could you add the topic? :)

**Comment by FoggyFinder** [comment]
> According to their website, a repo is only eligible for Hacktoberfest if it has the #hacktoberfest topic specified.

Can you quote the part you're referring to?

**Comment by jilleJr** [comment]
It's found in the "Maintainer" guide below the "Let's work together to reduce spam" section.

> [Apply the "Hacktoberfest" label](https://help.github.com/articles/applying-labels-to-issues-and-pull-requests/) to issues in your GitHub project that are ready for new contributors to work on.

It's also pronounced in the DEV.to blog posts by "The DEV team", example: https://dev.to/devteam/happy-hacktoberfest-here-s-how-to-show-up-for-open-source-this-month-4cee

> As a maintainer, be sure to[add hacktoberfest as a [topic to your repo](https://docs.github.com/en/free-pro-team@latest/github/administering-a-repository/classifying-your-repository-with-topics) in order to opt-in for Hacktoberfest contributions this month. If you don’t, participant’s PRs will not count towards their four PR-goal -- and your project won’t benefit from their additions.
>
>Here’s how to classify your project as Hacktoberfest-eligible:  
>![how-to-add-topic](https://res.cloudinary.com/practicaldev/image/fetch/s--Dc_Ygx2W--/c_limit%2Cf_auto%2Cfl_progressive%2Cq_66%2Cw_880/https://dev-to-uploads.s3.amazonaws.com/i/1n2czbtivbuls5wg0j1b.gif)

**Comment by FoggyFinder** [comment]
Update: [UPDATED: An update on efforts to reduce spam with Hacktoberfest: introducing maintainer opt-in and more](https://hacktoberfest.digitalocean.com/hacktoberfest-update)

**Comment by mattstermiller** [comment]
Done! Yes I wouldn't mind contributions at all. I am working on the 0.6.0 milestone but would take PRs for the other issues as well. Let me know if you have questions about the architecture, tests or requirements of any of the issues.

**Comment by jilleJr** [comment]
@mattstermiller Cool! Are you working ok ALL with 0.6.0 milestone or just some of them?
Just to avoid double-work.

I'll probably ask in the appropriate issue anyway of any task.

Tyty!

**Comment by mattstermiller** [comment]
The problem with most of the issues in 0.6.0 is they're fairly complex and need to be completed in a certain order because of co-dependence. There are 2 that would be good for new contributors though, so I've tagged those `help wanted`. I'll tag other such issues outside of this milestone as well.

**Comment by jilleJr** [comment]
Very considerate
