### ISSUE TITLE
Use keybindings (ex: j/k) in help panel

### ISSUE THREAD

**Issue by jilleJr** [mattstermiller/koffee#93]
**Describe the bug**
Cannot use keybindings in help panel.

**To Reproduce**
1. Open help panel by pressing `?` or `F1`
2. Try sort keybindings by name by pressing `sn`
3. Try search for keybinding by pressing `/`
4. Try scrolling down by pressing `j`

**Expected behavior**
Keybindings work in an equivalent way to the main view

**Workaround**
Use the mouse _(gosh!)_

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro, v2004, build 19041.508
 - Koffee Version: 0.5.2.0

**Additional context**
It would be nice to be able to refactor out this behaviour of the main panel to just be able to apply it to any listing. Such a refactoring could also come in handy in #20, as I suggested there to have keyboard selection support inside the history panel.

**Comment by mattstermiller** [comment]
Thanks for the suggestion! I want to spend some time thinking about how to design the settings window for better keyboard navigation. In the meantime, you can use the standard keys for navigating windows forms like Tab to focus the next field, space to toggle checkboxes, etc.

**Comment by mattstermiller** [comment]
I came up with a new design that will make settings navigable with the keyboard: #117. I'm closing this issue in favor of that one.
