### ISSUE TITLE
Navigate with environment variables, ex: %appdata%

### ISSUE THREAD

**Issue by jilleJr** [mattstermiller/koffee#94]
**Describe the bug**
Unable to navigate with Windows environment variables.
If I write `%appdata%` in the path field I'm confronted with the error message "Path format is invalid: `%appdata%

This is what I would consider a core-functionality of the Windows Explorer that I use every time I need to visit the AppData folder. Tedious to find it in Koffee.

Compositing environment variables isn't possible either in Koffee, but it's nice to be able to write `%homepath%/Desktop` to get to the desktop on anyone's machine.

**To Reproduce**
1. Open Koffee
2. Select the path field, either by pressing up-arrow or by clicking on it
3. Enter `%appdata%`

**Expected behavior**
Entered path results in `C:\Users\kalle\AppData\Roaming\`, or as with the `%homepath%/Desktop` example: `C:\Users\kalle\Desktop`

**Screenshots**
![image](https://user-images.githubusercontent.com/2477952/96297136-b220e500-0ff0-11eb-9f2b-cf08450d673e.png)

**Workaround**
If I promptly wanted to use the environment variables, then I would
- Open PowerShell
- ```ps1
  $env:APPDATA | clip
  ```
- Paste into the path field in Koffee

Otherwise I would just navigate to the folder manually, or just for the `%appdata%` example, I actually just have it bookmarked and navigate to it with that.

**Desktop (please complete the following information):**
- OS: Windows 10 Pro, v2004, build 19041.508
- Koffee Version: 0.5.2.0

**Additional context**
Here's a page on a lot of "Recognized Environment Variables (Windows 10)" over at Microsoft Docs: https://docs.microsoft.com/en-us/windows/deployment/usmt/usmt-recognized-environment-variables

Personally I can't get any of the `CSIDL_*` environment variables they mention to work in even regular Windows Explorer. But if they don't exist as environment variables for the user, then there's no need to fake them.

**Comment by jilleJr** [comment]
I'd like to tackle this as well if I'm allowed :)

**Comment by mattstermiller** [comment]
Haha of course! Thanks.
